services:
  nanobot-gateway:
    image: nanobot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${USERPROFILE}/.nanobot:/home/nanobottie/.nanobot
      - ${USERPROFILE}/.nanobot/oauth-cli-kit:/home/nanobottie/.local/share/oauth-cli-kit
    ports:
      - "18790:18790"
      - "18791:18791"
      - "18792:18792"
    command: ["gateway"]
    restart: unless-stopped
