services:
  nanobot-gateway:
    container_name: nanobot-gateway
    build:
      context: .
      dockerfile: Dockerfile
    image: nanobot
    command: ["gateway"]
    restart: unless-stopped
    ports:
      - "18790:18790"
      - "18791:18791"
      - "18792:18792"
    volumes:
      - ${USERPROFILE}/.nanobot:/home/nanobottie/.nanobot
      - ${USERPROFILE}/.nanobot/oauth-cli-kit:/home/nanobottie/.local/share/oauth-cli-kit
